# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  scheme = ENV['SCHEME']
  desc "Description of what the lane does"
  lane :do_release do
    # TODO: add bumping version number.
    prepare_build
    upload_prebuilt_binary
  end

  desc "Release dry run, all steps expect uploading release."
  lane :release_dry_run do 
    prepare_build
  end

  desc "Prepares build"
  private_lane :prepare_build do 
    xcclean(scheme: scheme)
    cocoapods
    scan(scheme: scheme, code_coverage: true)
    build_app(clean: true, scheme: scheme, skip_package_ipa: true)
    carthage(command: "build", no_skip_current: true)
    carthage(command: "archive", frameworks: "Uluru")
  end

  desc "Uploads prebuilt binary for carthage"
  private_lane :upload_prebuilt_binary do 
    github_release = set_github_release(
      repository_name: ENV['GITHUB_RELEASE_REPO'],
      api_token: ENV['GITHUB_TOKEN'],
      name: "WIP",
      tag_name: "1.0.0",
      commitish: "master",
      description: "WIP description",
      upload_assets: ["Uluru.framework.zip"]
    )
  end

end
