name: PR Check 

on: 
  push:
    branches:
      # Run on all branches 
      - '**'
  pull_request:
    branches:
      # Run on all branches 
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr-check:
    name: PR Check 
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.8
        bundler-cache: true
        
    - name: Run PR Check 
      run: |
        bundle exec fastlane pr_check
    